def get_correction_list():
    return {
    'phểp': 'phép',
    'trân': 'trên',
    'blến': 'biến',
    'kiển thức': 'kiến thức',
    'kï năng': 'kỹ năng',
    'kî năng': 'kỹ năng',
    'ไuyện': 'luyện',
    "phươ'ng": 'phương',
    'phương trinh': 'phương trình',
    'hâ': 'hệ',
    'bậc nhất hai ần': 'bậc nhất hai ẩn',
    'bằn': 'bằng',
    'lôgic': 'logic',
    'thuật ngữ': 'thuật ngữ',
    'chuong': 'chương',
    'bất': 'bất',
    'bài <br>': 'bài ',
    '<br>': '',
    ' vecto': ' vectơ',
    ' vecto ': ' vectơ ',
    'mạt phảng toa ગộ': 'mặt phẳng toạ độ',
    "bằngg": "bằng",
    "phện": "phân",
    "phện số": "phân số",
    "phện phối": "phân phối",
    "phện tích": "phân tích",
    "bù lổ": "bù lỗ",
    "kiển thúc": "kiến thức",
    "kiỹ năng": "kỹ năng",
    "chệu": "châu",
    "biều": "biểu",
    "biều đồ": "biểu đồ",
    "loai": "loại",
    "loai hai chiều": "loại hai chiều",
    "miền nghiệm của hệ bất phương tri̇nh": "miền nghiệm của hệ bất phương trình",
    "phưo'ng tri̇nh": "phương trình",
    "nhện": "nhân",
    "bình phương của nó bằngg 2": "bình phương của nó bằng 2",
    "ヨ": "\\exists",
    "biều đồ ven": "biểu đồ Ven",
    "biểu diến": "biểu diễn",
    "mổi": "mỗi",
    "hện": "hiện",
    "trục oxlà": "trục ox là",
    "trục oylà": "trục oy là",
    "nhoỏ": "nhỏ",
    "vi dụ": "ví dụ",
    "vidụ": "ví dụ",
    "vídụ": "ví dụ",
    "chện": "chân",
    "phện pháp": "phép pháp",
    "а)": "a)",
    "в)": "b)",
    "rổng": "rỗng", 
    "haitập": "hai tập", 
    "hoăc": "hoặc",
    "it": "ít", 
    "chiện": "chân",
    "kiến thú'c": "kiến thức", 
    "bù lỗ": "bù lỗ", 
    "b ằng": "bằng", 
    "viến thông": "viễn thông"
    }
